using C4WX1.Database.Models;
using C4WX1.DbMigrator.DataSeeders;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Serilog;

namespace C4WX1.Tests.Language
{
    public class LanguageApp : C4WX1App
    {
        protected override async ValueTask SetupAsync()
        {
            using var connection = new NpgsqlConnection(_container.GetConnectionString());
            await connection.ExecuteAsync("""
                CREATE TABLE "Language" (
                    "LanguageId" INTEGER GENERATED BY DEFAULT AS IDENTITY,
                    "Name" VARCHAR(500),
                    "FullName" VARCHAR(500),
                    CONSTRAINT "PK_Language" PRIMARY KEY ("LanguageId")
                );
                """);

            var serviceProvider = new ServiceCollection()
                .AddLogging(builder => builder.AddSerilog())
                .AddDbContext<THCC_C4WDEVContext>(options =>
                    options.UseNpgsql(_container.GetConnectionString()))
                .AddTransient<LanguageDataSeeder>()
                .BuildServiceProvider();

            using var scope = serviceProvider.CreateScope();
            var languageSeeder = scope.ServiceProvider.GetRequiredService<LanguageDataSeeder>();
            await languageSeeder.SeedAsync();

            await base.SetupAsync();
        }
    }
}
