namespace C4WX1.Tests.C4WDeviceToken
{
    public class C4WDeviceTokenApp : C4WX1App
    {
        protected override async ValueTask SetupAsync()
        {
            using var connection = new NpgsqlConnection(_container.GetConnectionString());
            await connection.ExecuteAsync("""
                CREATE TABLE "C4WDeviceToken" (
                    "C4WDeviceTokenId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "OldDeviceToken" TEXT,
                    "NewDeviceToken" TEXT,
                    "ClientEnvironment" TEXT,
                    "Device" TEXT,
                    "IsDeleted" BOOLEAN NOT NULL,
                    "CreatedDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                    "CreatedBy_FK" INTEGER NOT NULL,
                    "ModifiedDate" TIMESTAMP WITHOUT TIME ZONE,
                    "ModifiedBy_FK" INTEGER
                );
                """);

            await base.SetupAsync();
        }
    }
}
