global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'netcore-api'
    scheme: https
    tls_config:
      insecure_skip_verify: true  # Only for development - remove in production
    static_configs:
      - targets: ['host.docker.internal:7055'] 
    metrics_path: '/metrics'